### ISSUE TITLE
Spotlight Search

### ISSUE THREAD

**Issue by alexknipfer** [knipferrc/plate#209]
Add a spotlight search for filtering plates.

**Comment by knipferrc** [comment]
@alexknipfer Can we also make the search bar wider and more to the left?

**Comment by alexknipfer** [comment]
Seems like the most optimal way to achieve a search is using a reducer. https://github.com/apollostack/react-docs/blob/43a754861db343f7c1771d0b7d5238091b58f2dd/source/cache-updates.md#using-reducer
